development:
  adapter: postgresql
  host: localhost
  database: cubic
  username: jade
  password: codigo

test:
  adapter: postgresql
  host: localhost
  database: nscout_test
  template: cubic
  username: jade
  password: codigo

production:
  adapter: postgresql
  host: localhost
  database: cubic
  username: jade
  password: codigo
